### ISSUE TITLE
オープンソースありがとうございます

### ISSUE THREAD

**Issue by karubilee** [yukiasai/Nori#2]
swiftのコードだけですか？OCのコードがありますか？

**Comment by yukiasai** [comment]
@karubilee 実装はSwiftのみです。Objective-Cからも利用可能にすることはできると思います。もしかするともう利用できるようになっているかもしれませんが、確認してみます。

**Comment by karubilee** [comment]
コメントありがとうございました、必要になった時、やってみます。
